=== ondoheer/amnh-validation-tool/static/assets/json/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["recordData", "taxonomy", "determinedBy", "specimenData", "collectionData", "locationData", "donationData"],
    "definitions": {
        "person": {
            "type": "object",
            "properties": {
                "prefix": { "type": "string" },
                "firstName": { "type": "string" },
                "middleName1": { "type": "string" },
                "middleName2": { "type": "string" },
                "lastName1": { "type": "string" },
                "lastName2": { "type": "string" },
                "suffix": {"type": "string"}
            },
            "additionalProperties": false
        }
    },
    "properties": {
        "id": {"type": "integer"},
        "recordData":{
            "type": "object",
            "properties": {
                "trackingNumber": { "type": "string"},
                "catalogNumber": { "type": "string" },
                "barcodeNumber": { "type": "string" },
                "collectionSubset": { "type": "string" },
                "notes": { "type": "string" }
            },
            "additionalProperties": false
        },
        "taxonomy": {
            "type": "object",
            "properties": {
                "verbatim": { "type": "string" },
                "class": { "type": "string" },
                "subclass": { "type": "string" },
                "order": { "type": "string" },
                "suborder": { "type": "string" },
                "family": { "type": "string" },
                "genus": { "type": "string" },
                "species": { "type": "string" },
                "notes": { "type": "string" }
            },
            "additionalProperties": false
        },
        "determinedBy":{
            "type":"object",
            "properties": {
                "verbatim": { "type": "string" },
                "year": { "type": "string" },
                "people": {            
                    "type": "array",
                    "items": { "$ref": "#/definitions/person" }
                },
                "notes": {"type":"string"}
            },
            "additionalProperties": false
        },
        "specimenData": {
            "type": "object",
            "properties": {
                "numberOfSpecimens": { "type": "integer" },
                "storageMedium": { "type": "string" },
                "typeOfType": { "type": "string" },
                "sex": { "enum": ["male", "female"] },
                "developmentStage": { "type": "string" },
                "bodyPartLocation": { "type": "string" },
                "hasHost": {"type": "boolean"},
                "hostData": {
                    "type": "object",
                    "properties": {
                        "catalogNumber": { "type": "integer" },
                        "relationship": { "type": "string" },
                        "species": { "type": "string" },
                        "genus": { "type": "string" },
                        "sex": { "enum": ["male", "female"] },
                        "condition": { "type": "string" },
                        "notes": { "type": "string" }
                    }
                },
                "notes": { "type": "string" }
            },
            "additionalProperties": false
        },
        "collectionData": {
            "type": "object",
            "properties": {
                "method": { "type": "string" },
                "relationship": { "type": "string" },
                "verbatiamDate": { "type": "string" },
                "fromDate": { "type": "string" },
                "toDate": { "type": "string" },
                "expeditionName": { "type": "string" },
                "notes": { "type": "string" },
                "verbatimCollectors": { "type": "string" },
                "collectors": {
                    "type":"array",
                    "items": { "$ref": "#/definitions/person" }
                }
            },
            "additionalProperties": false
        },
        "locationData":{
            "type": "object",
            "properties": {
                "verbatim": {"type":"string"},
                "continent": {"type": "string"},
                "ocean": {"type": "string"},
                "seaGulfStrait": {"type": "string"},
                "lakePondReservoir": {"type": "string"},
                "bayHarbor": {"type": "string"},
                "riverCreek": {"type": "string"},
                "stream": {"type": "string"},
                "mountainRange": {"type": "string"},
                "mountain": {"type": "string"},
                "islandGroup": {"type": "string"},
                "island": {"type": "string"},
                "country": {"type": "string"},
                "department": {"type": "string"},
                "county": {"type": "string"},
                "cityTownHamlet": {"type": "string"},
                "specificLocale": {"type": "string"},
                "temperature": {
                    "type": "object",
                    "properties": {
                        "celsius": {"type": "number"},
                        "fahrenheit": {"type": "number"}
                    }
                },
                "fromLat": {"type": "string"},
                "fromLon": {"type": "string"},
                "toLat": {"type": "string"},
                "toLon": {"type": "string"},
                "notes": {"type":"string"}
            },
            "additionalProperties": false
        },
        "donationData":{
            "type": "object",
            "properties": {
                "verbatim": { "type": "string" },
                "donors": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/person" }
                },
                "date": {"type":"string"},
                "notes": {"type": "string"}
            },
            "additionalProperties": false
        }  
    }
}

=== ondoheer/amnh-validation-tool/static/assets/json/example.json
{
    "id": 1,
    "recordData": {
        "trackingNumber": "MD123456",
        "catalogNumber": "1234567",
        "barcodeNumber": "12345678",
        "collectionSubset": "Some Collection",
        "notes": "Very nice record"
    },
    "taxonomy": {
        "verbatim": "Great sea snail",
        "class": "Slugs",
        "subclass": "Slugs with shells",
        "order": "Larger slugs",
        "suborder": "Even larger slugs",
        "family": "",
        "genus": "",
        "species": "",
        "notes": "Its a very nice snail"
    },
    "determinedBy": {
        "verbatim": "Jane Doe",
        "year": "1992",
        "people": [
            {
                "prefix": "Ms",
                "firstName": "Jane",
                "middleName1": "Mary",
                "middleName2": "Whitney",
                "lastName1": "Doe",
                "lastName2": "Monroe",
                "suffix": "PhD"
            }
        ],
        "notes": "Very smart person"
    },
    "specimenData": {
        "numberOfSpecimens": 1,
        "storageMedium": "eth0",
        "typeOfType": "some type",
        "sex": "male",
        "developmentStage": "Adult",
        "bodyPartLocation": "Shell",
        "hasHost": false,
        "notes": "Very nice specimen"
    },
    "collectionData": {
        "method": "Fingers",
        "relationship": "Strong",
        "verbatiamDate": "MXXVIII",
        "fromDate": "1992-09-10-10-10",
        "toDate": "1992-09-10-10-10",
        "expeditionName": "Epic Snail Trek",
        "notes": "Tricky to catch",
        "verbatimCollectors": "Jane Doe",
        "collectors": [
            {
                "prefix": "Ms",
                "firstName": "Jane",
                "middleName1": "Mary",
                "middleName2": "Whitney",
                "lastName1": "Doe",
                "lastName2": "Monroe",
                "suffix": "PhD"
            }
        ]
    },
    "locationData": {
        "verbatim": "Next to a pond",
        "continent": "",
        "ocean": "",
        "seaGulfStrait": "",
        "lakePondReservoir": "",
        "bayHarbor": "",
        "riverCreek": "",
        "stream": "",
        "mountainRange": "",
        "mountain": "",
        "islandGroup": "",
        "island": "",
        "country": "",
        "department": "",
        "county": "",
        "cityTownHamlet": "",
        "specificLocale": "",
        "temperature": {
            "celsius": 10.6,
            "fahrenheit": 40.8
        },
        "fromLat": "10.290.90",
        "fromLon": "30.918.23",
        "toLat": "98324.234.2",
        "toLon": "13123.123.23",
        "notes": "Beautiful Location"
    },
    "donationData": {
        "verbatim": "Jane Doe",
        "donors": [
            {
                "prefix": "Ms",
                "firstName": "Jane",
                "middleName1": "Mary",
                "middleName2": "Whitney",
                "lastName1": "Doe",
                "lastName2": "Monroe",
                "suffix": "PhD"
            }
        ],
        "date": "1923-12-3-12-32",
        "notes": "Jane does everything"
    }
}
